config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: [:index, :show] do
    get "youtube"
  end
  resources :events, only: [:index, :show]
  resources :venues, only: [:index, :show]

  root 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :artist_events
  has_many :events, through: :artist_events

  default_scope { order(:name) }

  validates :name, presence: true
end

app/models/artist_event.rb
class ArtistEvent < ActiveRecord::Base
  @table_name = "artists_events"

  belongs_to :artist
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  PRICE_REGEX = /\$[[:digit:]]+\.[[:digit:]]{2,}/

  belongs_to :venue
  has_many :artist_events
  has_many :artists, through: :artist_events

  default_scope { order(:starts_at) }
  scope :upcoming, -> { where("starts_at > ?", Time.now.getlocal) }

  validates :venue, presence: true
  validates :starts_at, presence: true
  validates :soldout, inclusion: { in: [true, false],
                                   message: "requires a true or false value" }

  # Returns the price in currency as a float
  def price
    price_cent / 100.0
  end

  def price=(price)
    self.price_cent = if price.is_a?(String) && price.match(PRICE_REGEX)
                        (price.delete("$").to_f * 100).to_i
                      elsif price.is_a?(Float)
                        (float_price * 100).to_i
                      else
                        price
                      end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events

  default_scope { order(:name) }

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
require "google/apis/youtube_v3"

class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :youtube]
  before_action :set_upcoming_events, only: [:show]

  YT = ::Google::Apis::YoutubeV3

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    youtube
    soundcloud
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artist
    @artist = Artist.find(params[:id] || params[:artist_id])
  end

  def set_upcoming_events
    @upcoming_events = @artist.events.upcoming
  end

  def set_sample_track(client)
    # Cache the track for next time
    @artist.sample_track ||= client.get("/tracks", q: @artist.name).first
    @artist.save!
  end

  def youtube
    client = YT::YouTubeService.new
    client.key = ENV["GOOGLE_DEVELOPER_KEY"]

    begin
      search_result = client.list_searches("id", q: @artist.name,
                                                 max_results: 1, type: "video")
      @video_id = search_result.items.first.id.video_id
    rescue => e
      logger.error "ERROR: Looks like youtube is broken"
      logger.error e.message
    end
  end

  def soundcloud
    client = Soundcloud.new(client_id: ENV["SOUNDCLOUD_CLIENT_ID"])

    begin
      set_sample_track(client)

      # If we found some tracks, lets show a one
      if @artist.sample_track.present?
        url = @artist.sample_track["permalink_url"]
        @soundcloud_oembed = client.get("/oembed", url: url)
      end
    rescue => e
      logger.error "Looks like soundcloud is broken:"
      logger.error e.message
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.upcoming
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @venue = @event.venue
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show]
  before_action :set_upcoming_events, only: [:show]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.find(params[:id])
  end

  def set_upcoming_events
    @upcoming_events = @venue.events.upcoming
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def when_and_where(event)
    "#{I18n.l(event.starts_at, format: :long)} at #{event.venue.name}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_title(event)
    artists_name = event.artists.map(&:name).join(" + ")
    "#{artists_name} playing at #{event.venue.name}"
  end

  def nice_soldout(soldout)
    soldout ? "All gone" : "Not yet"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/application/_upcoming_events.html.erb
<h2>Upcoming events</h2>
<% if upcoming_events.present? %>
  <table>
    <thead>
      <tr>
        <th>When and where</th>
      </tr>
    </thead>

    <tbody>
      <% upcoming_events.each do |event| %>
        <tr>
          <td><%= link_to(when_and_where(event), event)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Sorry there are no upcoming events for this artist</p>
<% end %>

app/views/artists/_soundcloud.html.erb
<% if @soundcloud_oembed %>
  <%# Ewwww!!! Don't like using html_safe %>
  <%= @soundcloud_oembed['html'].html_safe %>
<% else %>
  <p>Sorry, we couldn't find anything to preview for you...</p>
<% end %>

app/views/artists/_youtube.html.erb
<!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
<div id="player"></div>

<script>
  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.
  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: '640',
      videoId: '<%= @video_id %>',
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }

  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
    event.target.playVideo();
  }

  // 5. The API calls this function when the player's state changes.
  //    The function indicates that when playing a video (state=1),
  //    the player should play for six seconds and then stop.
  var done = false;
  function onPlayerStateChange(event) {
    if (event.data == YT.PlayerState.PLAYING && !done) {
      setTimeout(stopVideo, 6000);
      done = true;
    }
  }
  function stopVideo() {
    player.stopVideo();
  }
</script>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to 'Show', artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @artist.name %></h1>

<%= render partial: "application/upcoming_events", locals: {upcoming_events: @upcoming_events } %>

<h2>Preview a tune</h2>

<div>
  <%= render partial: "artists/youtube", locals: {video_id: @video_id} %>
  <%= render partial: "artists/soundcloud", locals: {soundcloud_oembed: @soundcloud_oembed} %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Who? What? Where?</th>
      <th>Starts at</th>
      <th>Price</th>
      <th>Soldout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event_title(event) %></td>
        <td><%= time_tag(event.starts_at) %></td>
        <td><%= number_to_currency(event.price, precision: 2) %></td>
        <td><%= nice_soldout(event.soldout) %></td>
        <td><%= link_to('Show', event)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= event_title(@event) %></h2>

<h3>Who's playing</h3>
<% @event.artists.each do |a| %>

<p><%= link_to(a.name, artist_path(a)) %></p>
<% end %>

<h3>Playing at</h3>
<p>
  <%= link_to(@venue.name, venue_path(@venue)) %>
</p>

<h3>What are the gig details</h3>
<p>
  <strong>Starts at:</strong>
  <%= time_tag(@event.starts_at) %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@event.price, precision: 2) %>
</p>

<p>
  <strong>Soldout:</strong>
  <%= nice_soldout(@event.soldout) %>
</p>

app/views/home/index.html.erb
<h2>Welcome</h2>
<p>
We want to create an online resource where music lovers can visit to know what
band is coming to Montreal soon and when and where and be able to
preview/listen to at least a song to have an idea.
</p>

<p>
This was developed as part of a coding challenge. See the
<%= link_to "github page", "https://github.com/steakunderscore/cheap-thrills" %>
for more information.
</p>

app/views/layouts/_footer.html.erb
<div>
  <p>Cheap thrills previewer &copy; <%= Time.zone.now.year %></p>
</div>

app/views/layouts/_menu.html.erb
<h1><%= link_to "Cheap Thrills", root_path %></li>

<ul>
  <li><%= link_to "Upcoming Events", events_path %></li>
  <li><%= link_to "Checkout Artists", artists_path %></li>
  <li><%= link_to "Venues", venues_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheapThrills</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/menu" %>

<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= link_to 'Show', venue %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<%= render partial: "application/upcoming_events", locals: {upcoming_events: @upcoming_events } %>